### PR TITLE
Deduplicate API requests made from the Allocations page

### LINKED ISSUE #88: Allocation API is fetched twice per request
**Describe the bug**
Opencost UI during the first-time load of the page or data refreshes, calls the allocation endpoint twice instead of once. These are duplicate requests which can reduce the net performance of the website

**To Reproduce**
Go to the demo URL and inspect the network

**Expected behavior**
The API should be called only once

**Screenshots**
Image

**Which version of OpenCost are you using?**
[You can find the version from the container's startup logging or from the bottom of the page in the UI.](https://demo.infra.opencost.io/?window=today&agg=namespace&currency=UGX&acc=false)

**Additional context**
The background has a side-effect that looks for `fetch` variable that if set to "true" runs `fetchData`. `setFetchData(true)` is invoked during a refresh or a page load, this calls the side-effect from above to update the table by calling the /allocation endpoint. The problem here is that the `fetchData` function takes quite a while to run and it only sets `fetch` to "false" at the end of the function's execution. Within this time, the side-effect calls `fetchData` function again.

### PR DESCRIPTION
**Pull request by nealormsbee**
## What does this PR change?
A few things:
* Remove unused imports from the pages/CloudCosts.js
* Update the setLogLevel function of the Logger to disregard and warn on invalid log level settings, so that it doesn't allow itself to reach a bad state.
* Change the initialization / data loading implementation of pages/Allocations.js to prevent double-loading data on page load & subsequent changes. Also conforms better to React norms.

## Does this PR relate to any other PRs?
* No.

## How will this PR impact users?
* Page load efficiency will be improved by deduplicating a potentially expensive XHR request.

## Does this PR address any GitHub or Zendesk issues?
* Closes #88 

## How was this PR tested?
* Manually by pointing the opencost ui in dev-mode at https://demo.infra.opencost.io/model and observing that the duplicate requests have stopped. Video clip below.

https://github.com/user-attachments/assets/e38c1afc-d665-4b1c-b1d2-12cf99209702

## Does this PR require changes to documentation?
* No.

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
* It has not been marked as such.

### CODE REVIEW

File: src/pages/CloudCosts.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ import Footer from "../components/Footer";
 import IconButton from "@material-ui/core/IconButton";
 import RefreshIcon from "@material-ui/icons/Refresh";
 import { makeStyles } from "@material-ui/styles";
-import { Box, Link, Paper, Typography } from "@material-ui/core";
```
Comment (nealormsbee) [inline src/pages/CloudCosts.js]: The two imports deleted from this file are unused.

File: src/services/logger.js [hunk 2]
```diff
@@ -50,7 +50,14 @@ function createLogger(level = defaultLogLevel) {
...
   logger.setLogLevel = function (logLevel) {
-    this._logLevel = logLevel;
+    if (logLevels.includes(logLevel)) {
+      this._logLevel = logLevel;
+    } else {
+      console.warn(
+        `Attempting to set unrecognized log level: ${logLevel}. Skipping.`
+      );
+      console.warn(`Valid log levels are ${logLevels.join(", ")}`);
+    }
```
Comment (nealormsbee) [inline src/services/logger.js]: The goal here is to help prevent users from misconfiguring the logger by rejecting invalid log level sets.

File: src/pages/Allocations.js [hunk 3]
```diff
@@ -80,7 +80,7 @@ function generateTitle({ window, aggregateBy, accumulate }) {
   let aggregationName = get(
     find(aggregationOptions, { value: aggregateBy }),
     "name",
-    "",
+    ""
```
Comment (nealormsbee) [inline src/pages/Allocations.js]: A high level explanation of these changes is as follows:

* Remove the `initialize()` function, which did nothing, and the `init` state variable that was used to trigger the `useEffect` callback that ran `initialize()`.
* Also remove the `fetch` state variable, and most of the state variables for page controls (aggregation, window, etc). The `fetchData()` function is now called:
  * On page load
  * When window, aggregate, or accumulate change
  * When the user clicks the "refresh" button
* No more watching those state vars, to then toggle a `fetch` state variable, to trigger a useEffect which runs `fetchData()`.
* Instead of watching the `searchParams` with a `useEffect`, and updating the state variables when the query params change, we now instead just drive the page state _through_ the query params. This was already happening - we're just cutting out a useless middleman here.

**Comment by ameijer** [comment]
tested out the netlify deployment, looks good to me!
